Repository jenkinsci/flaky-test-handler-plugin, pull requests merged in 2021-03, with the labels that each got.

#15 Move documentation to GitHub
  README.md
  images/deflake_build.png
  images/deflake_checkout_config.png
  images/deflake_config.png
  images/deflake_label.png
  images/flake_history_aggregated.png
  images/flake_history_single.png
  images/flaky_badge.png
  images/flaky_config1.png
  images/flaky_pass.png
  pom.xml
Labels: enhancement

#17 Fix HistoryAggregatedFlakyTestResultActionTest on Windows
  src/test/java/com/google/jenkins/flakyTestHandler/plugin/HistoryAggregatedFlakyTestResultActionTest.java
Labels: internal

#18 Enable Release Drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: skip-changelog
